import { useEffect, useRef, useState, useSyncExternalStore, type FormEvent, type ReactNode } from 'react'
import { ArrowDownToLine, ArrowUpFromLine, ArrowUpRight, Check, CheckCircle2, ChevronLeft, ChevronRight, CloudUpload, Copy, File, Files, FolderClosed, HardDrive, LayoutDashboard, Link2, LoaderCircle, LockKeyhole, LogOut, Menu, MoreHorizontal, Pause, Play, Plus, RefreshCw, Search, Settings2, ShieldCheck, Trash2, Upload, X } from 'lucide-react'
import { api, ApiError, bytes, date, duration, message, setCSRF, type FileItem, type FileList, type Settings, type Stats, type User } from './api'
import { UploadQueue, type Task } from './upload'

type Notify = (text: string, error?: boolean) => void
function Logo({ light = false }: { light?: boolean }) { return <div className={`brand ${light ? 'brand-light' : ''}`}><span className="brand-mark"><Link2 size={24} strokeWidth={2.7} /></span><span>LinkBox<span className="brand-send">Send</span></span></div> }
function Spinner() { return <div className="loading"><LoaderCircle className="spin" size={26} /><span>正在加载…</span></div> }
function Empty({ children }: { children: ReactNode }) { return <div className="empty"><FolderClosed size={34} strokeWidth={1.3} /><p>{children}</p></div> }
function ErrorBox({ error }: { error: string }) { return error ? <div role="alert" className="error-box">{error}</div> : null }
function useResource<T>(path: string, refresh = 0) {
  const [data, setData] = useState<T>(); const [error, setError] = useState('')
  useEffect(() => { let alive = true; setError(''); api<T>(path).then(v => { if (alive) setData(v) }).catch(e => { if (alive) setError(message(e)) }); return () => { alive = false } }, [path, refresh])
  return { data, error }
}
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) {
  const ref = useRef<HTMLDialogElement>(null)
  useEffect(() => { ref.current?.showModal(); const dialog = ref.current; return () => dialog?.close() }, [])
  return <dialog ref={ref} className="modal" onCancel={onClose} onClick={e => { if (e.target === ref.current) onClose() }}><div className="modal-head"><h2>{title}</h2><button className="icon-button" aria-label="关闭" onClick={onClose}><X size={20} /></button></div>{children}</dialog>
}

export default function App() {
  const [user, setUser] = useState<User | null>(); const [settings, setSettings] = useState<Settings>(); const [error, setError] = useState('')
  const [notice, setNotice] = useState<{ text: string; error?: boolean }>()
  const notify: Notify = (text, error) => setNotice({ text, error })
  useEffect(() => { if (notice) { const id = setTimeout(() => setNotice(undefined), 5500); return () => clearTimeout(id) } }, [notice])
  const acceptSession = async (data: { user: User; csrfToken: string }) => { setCSRF(data.csrfToken); const config = await api<Settings>('/settings'); setSettings(config); setUser(data.user) }
  const isShare = window.location.pathname.startsWith('/s/')
  useEffect(() => { if (isShare) return; api<{ user: User; csrfToken: string }>('/auth/me').then(acceptSession).catch(e => { if (e instanceof ApiError && e.status === 401) setUser(null); else setError(message(e)) }) }, [isShare])
  if (isShare) return <SharePage token={window.location.pathname.split('/')[2] || ''} />
  return <>{user === undefined ? <div className="boot"><Logo /><ErrorBox error={error} />{!error && <Spinner />}{error && <button className="button" onClick={() => location.reload()}>重新连接</button>}</div> : user === null ? <Login onLogin={acceptSession} /> : settings ? <Workspace key={user.id} user={user} settings={settings} notify={notify} onLogout={async () => { await api('/auth/logout', { method: 'POST' }); setCSRF(''); setUser(null) }} /> : <Spinner />}
    {notice && <div role="status" className={`toast ${notice.error ? 'toast-error' : ''}`}>{notice.error ? <X size={18} /> : <CheckCircle2 size={18} />}{notice.text}<button aria-label="关闭提示" onClick={() => setNotice(undefined)}><X size={16} /></button></div>}
  </>
}
function Login({ onLogin }: { onLogin: (v: { user: User; csrfToken: string }) => Promise<void> }) {
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(''); const data = new FormData(e.currentTarget); try { await onLogin(await api('/auth/login', { method: 'POST', body: JSON.stringify({ username: data.get('username'), password: data.get('password') }) })) } catch (e) { setError(message(e)) } finally { setBusy(false) } }
  return <div className="login-page"><section className="login-art"><Logo light /><div className="login-copy"><span className="eyebrow">YOUR FILES. YOUR SPACE.</span><h1>大文件，<br />轻松抵达<span>。</span></h1><p>把灵感、作品和重要资料，<br />送到它们该去的地方。</p><div className="orbit"><div className="orbit-center"><Upload size={46} /></div><span className="orbit-file orbit-file-one"><File size={26} /> design.zip</span><span className="orbit-file orbit-file-two"><CheckCircle2 size={22} /> 已安全送达</span></div></div><div className="login-footer"><ShieldCheck size={16} /> 私有空间 · 安全传输 · 自由分享</div></section><section className="login-form"><div className="mobile-logo"><Logo /></div><div className="login-form-inner"><span className="eyebrow">WELCOME BACK</span><h2>欢迎回到你的空间</h2><p className="muted">登录 LinkBox Send，开始传递下一份精彩。</p><form onSubmit={submit}><label>用户名<input name="username" autoComplete="username" required autoFocus placeholder="输入用户名" maxLength={64} /></label><label>密码<input name="password" type="password" autoComplete="current-password" required placeholder="输入密码" maxLength={72} /></label><ErrorBox error={error} /><button className="button primary full" disabled={busy}>{busy ? <LoaderCircle className="spin" size={18} /> : <>登录空间 <ArrowUpRight size={18} /></>}</button></form><div className="login-note"><LockKeyhole size={15} /> 仅受邀用户可访问。请联系管理员获取账号。</div></div><span className="login-copyright">LinkBox Send · Made for the way you share.</span></section></div>
}

function Workspace({ user, settings, notify, onLogout }: { user: User; settings: Settings; notify: Notify; onLogout: () => Promise<void> }) {
  const [path, setPath] = useState(window.location.pathname); const [mobileNav, setMobileNav] = useState(false)
  const [queue] = useState(() => new UploadQueue(settings, user.id)); const tasks = useSyncExternalStore(queue.subscribe, queue.getSnapshot)
  const [refresh, setRefresh] = useState(0); const [sharing, setSharing] = useState<FileItem>(); const [deleting, setDeleting] = useState<FileItem>()
  const [deleteBusy, setDeleteBusy] = useState(false)
  const completed = tasks.filter(t => t.status === 'complete').length
  const stats = useResource<Stats>('/dashboard', refresh + completed)
  useEffect(() => () => queue.dispose(), [queue])
  useEffect(() => { const handler = () => setPath(location.pathname); window.addEventListener('popstate', handler); return () => window.removeEventListener('popstate', handler) }, [])
  const navigate = (next: string) => { history.pushState({}, '', next); setPath(next); setMobileNav(false) }
  const active = tasks.filter(t => !['complete', 'canceling'].includes(t.status)).length
  const nav = [{ path: '/', name: '总览', en: 'Overview', icon: LayoutDashboard }, { path: '/upload', name: '上传文件', en: 'Upload', icon: CloudUpload }, { path: '/files', name: '我的文件', en: 'My files', icon: Files }, { path: '/settings', name: '设置', en: 'Settings', icon: Settings2 }]
  const current = nav.find(n => n.path === path) || nav[0]
  async function remove() { if (!deleting) return; setDeleteBusy(true); try { await api(`/files/${deleting.id}`, { method: 'DELETE' }); setDeleting(undefined); setRefresh(n => n + 1); notify('文件及其分享已删除') } catch (e) { notify(message(e), true) } finally { setDeleteBusy(false) } }
  return <div className="workspace">{mobileNav && <button className="nav-scrim" aria-label="收起菜单" onClick={() => setMobileNav(false)} />}
    <aside className={`sidebar ${mobileNav ? 'sidebar-open' : ''}`}><Logo light /><div className="workspace-label">个人工作空间</div><nav>{nav.map(n => <button key={n.path} className={`nav-item ${current.path === n.path ? 'nav-active' : ''}`} onClick={() => navigate(n.path)}><n.icon size={20} /><span>{n.name}</span>{n.path === '/upload' && active > 0 && <b>{active}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="private-badge"><ShieldCheck size={18} /><div><strong>你的文件，由你掌控</strong><p>独立存储，私密分享</p></div></div><div className="sidebar-rule" /><button className="account" onClick={() => navigate('/settings')}><span className="avatar">{user.username.slice(0, 2).toUpperCase()}</span><span><strong>{user.username}</strong><small>{user.role === 'admin' ? '管理员' : '个人账号'}</small></span><MoreHorizontal size={19} /></button><button className="logout" onClick={() => onLogout().catch(e => notify(message(e), true))}><LogOut size={15} /> 退出登录</button></div></aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="打开菜单" onClick={() => setMobileNav(true)}><Menu size={22} /></button><span>工作空间</span><ChevronRight size={14} /><strong>{current.name}</strong></div><div className="topbar-right"><span className="secure-label"><span /> 私有传输空间</span><span className="topbar-divider" /><span className="avatar avatar-small">{user.username.slice(0, 1).toUpperCase()}</span></div></header>
      <main><div className="page-heading"><div><span className="eyebrow">{current.en.toUpperCase()}</span><h1>{current.path === '/' ? '每一份文件，都有去处。' : current.name}</h1><p className="muted">{current.path === '/' ? `你好，${user.username}。你的文件空间已准备就绪。` : current.path === '/upload' ? '从这里出发，让大文件轻松抵达。' : current.path === '/files' ? '整理你的文件，用一个链接与世界分享。' : '按你的习惯，设置自己的传输空间。'}</p></div>{current.path !== '/upload' && current.path !== '/settings' && <button className="button primary" onClick={() => navigate('/upload')}><Plus size={18} /> 上传文件</button>}</div>
      {current.path === '/' && <Dashboard stats={stats.data} error={stats.error} refresh={refresh + completed} tasks={tasks} navigate={navigate} share={setSharing} remove={setDeleting} />}
      {current.path === '/upload' && <UploadPage queue={queue} tasks={tasks} settings={settings} notify={notify} onFiles={() => navigate('/files')} />}
      {current.path === '/files' && <FilesPage refresh={refresh + completed} share={setSharing} remove={setDeleting} />}
      {current.path === '/settings' && <SettingsPage user={user} settings={settings} queue={queue} notify={notify} onPasswordChanged={() => location.reload()} />}
      </main><footer className="page-footer"><span>LinkBox Send</span><span>Small link. Big possibilities.</span></footer>
    </div>
    {sharing && <ShareModal file={sharing} notify={notify} onClose={() => { setSharing(undefined); setRefresh(n => n + 1) }} />}
    {deleting && <Modal title="删除文件" onClose={() => !deleteBusy && setDeleting(undefined)}><p className="modal-description">确定删除「{deleting.name}」？实际文件和所有分享链接都会被删除，此操作无法撤销。</p><div className="modal-actions"><button className="button" disabled={deleteBusy} onClick={() => setDeleting(undefined)}>保留文件</button><button className="button danger" disabled={deleteBusy} onClick={remove}>{deleteBusy ? '正在删除…' : '删除文件'}</button></div></Modal>}
  </div>
}

function Dashboard({ stats, error, refresh, tasks, navigate, share, remove }: { stats?: Stats; error: string; refresh: number; tasks: Task[]; navigate: (p: string) => void; share: (f: FileItem) => void; remove: (f: FileItem) => void }) {
  const recent = useResource<FileList>('/files', refresh)
  const percent = stats ? Math.min(100, stats.usedStorage / stats.totalStorage * 100) : 0
  return <><ErrorBox error={error} /><div className="overview-grid"><div className="welcome-card"><div className="welcome-icon"><CloudUpload size={32} strokeWidth={1.5} /></div><div><span className="mini-label">READY WHEN YOU ARE</span><h2>分享，从上传开始</h2><p>大型设计稿、高清视频、项目归档。<br />无论多大，都能从容发送。</p></div><button className="button dark" onClick={() => navigate('/upload')}>选择文件 <ArrowUpRight size={17} /></button><div className="welcome-decoration"><File size={84} strokeWidth={0.7} /></div></div><div className="storage-card"><div className="section-top"><span><HardDrive size={18} /> 存储空间</span><span className="pill dark-pill">VPS</span></div><div className="storage-amount">{stats ? bytes(stats.availableStorage) : '—'}<span>可用空间</span></div><div className="storage-track"><span style={{ width: `${percent}%` }} /></div><div className="storage-caption"><span>已使用 {stats ? bytes(stats.usedStorage) : '—'}</span><span>共 {stats ? bytes(stats.totalStorage) : '—'}</span></div><div className="storage-note">包含系统占用 · 另保留 {stats ? bytes(stats.reservedStorage) : '—'} 安全空间</div></div></div>
    <div className="stats-grid">{[{ title: '我的文件', value: stats?.fileCount.toLocaleString() ?? '—', unit: '个文件', icon: Files, color: 'purple' }, { title: '上传中的任务', value: stats?.activeUploads.toString() ?? '—', unit: tasks.some(t => t.status === 'uploading') ? '正在传输' : '等待 / 传输中', icon: CloudUpload, color: 'green' }, { title: '今日上传', value: stats ? bytes(stats.todayUploaded) : '—', unit: 'UTC 今日流量', icon: ArrowUpFromLine, color: 'orange' }, { title: '今日下载', value: stats ? bytes(stats.todayDownloaded) : '—', unit: 'UTC 今日流量', icon: ArrowDownToLine, color: 'blue' }].map(card => <div className="stat-card" key={card.title}><div className="stat-title">{card.title}<span className={`stat-icon ${card.color}`}><card.icon size={18} /></span></div><strong>{card.value}</strong><small>{card.unit}</small></div>)}</div>
    <section className="panel"><div className="panel-heading"><div><h2>最近上传</h2><p>灵感与资料，都在这里。</p></div><button className="text-button" onClick={() => navigate('/files')}>查看全部 <ArrowUpRight size={16} /></button></div><ErrorBox error={recent.error} />{recent.data ? <FileTable files={recent.data.files.slice(0, 5)} share={share} remove={remove} /> : <Spinner />}</section>
    <div className="tip-line"><ShieldCheck size={18} /><span>文件保存在你的服务器中。分享时可以设置密码、有效期和下载次数。</span></div>
  </>
}
function FilesPage({ refresh, share, remove }: { refresh: number; share: (f: FileItem) => void; remove: (f: FileItem) => void }) {
  const [search, setSearch] = useState(''); const [sort, setSort] = useState('newest'); const [page, setPage] = useState(1)
  const files = useResource<FileList>(`/files?search=${encodeURIComponent(search)}&sort=${sort}&page=${page}`, refresh)
  return <section className="panel"><div className="file-toolbar"><div className="search-input"><Search size={18} /><input aria-label="搜索文件" placeholder="搜索文件名称…" value={search} onChange={e => { setSearch(e.target.value); setPage(1) }} /></div><select aria-label="排序方式" value={sort} onChange={e => { setSort(e.target.value); setPage(1) }}><option value="newest">最近上传</option><option value="oldest">最早上传</option><option value="name">名称 A → Z</option><option value="largest">文件从大到小</option><option value="smallest">文件从小到大</option></select></div><ErrorBox error={files.error} />{files.data ? <><FileTable files={files.data.files} share={share} remove={remove} /><div className="pagination"><span>共 {files.data.total} 个文件</span><div><button className="icon-button" aria-label="上一页" disabled={page <= 1} onClick={() => setPage(p => p - 1)}><ChevronLeft size={18} /></button><span>第 {page} 页</span><button className="icon-button" aria-label="下一页" disabled={page * files.data.pageSize >= files.data.total} onClick={() => setPage(p => p + 1)}><ChevronRight size={18} /></button></div></div></> : <Spinner />}</section>
}
function FileTable({ files, share, remove }: { files: FileItem[]; share: (f: FileItem) => void; remove: (f: FileItem) => void }) {
  if (!files.length) return <Empty>还没有文件，上传第一份文件开启分享。</Empty>
  return <div className="table-scroll"><table><thead><tr><th>文件名称</th><th>大小</th><th>上传时间</th><th>分享</th><th className="text-right">操作</th></tr></thead><tbody>{files.map(f => <tr key={f.id}><td><div className="file-cell"><span className={`file-icon ${f.mimeType.startsWith('image/') ? 'purple' : f.mimeType.startsWith('video/') ? 'orange' : 'blue'}`}><File size={23} strokeWidth={1.5} /></span><div><strong title={f.name}>{f.name}</strong><details className="file-hash"><summary>SHA-256 · {f.sha256.slice(0, 12)}…</summary><code>{f.sha256}</code></details>{f.status === 'deleting' && <small className="red-text">删除待重试</small>}</div></div></td><td className="nowrap">{bytes(f.size)}</td><td className="nowrap">{date(f.createdAt)}</td><td><span className="share-count"><Link2 size={13} />{f.shareCount}</span></td><td><div className="row-actions"><button className="icon-button" aria-label={`分享 ${f.name}`} title="创建 / 管理分享" onClick={() => share(f)} disabled={f.status !== 'ready'}><Link2 size={18} /></button><button className="icon-button delete-button" aria-label={`删除 ${f.name}`} title="删除文件" onClick={() => remove(f)}><Trash2 size={17} /></button></div></td></tr>)}</tbody></table></div>
}

function UploadPage({ queue, tasks, settings, notify, onFiles }: { queue: UploadQueue; tasks: Task[]; settings: Settings; notify: Notify; onFiles: () => void }) {
  const input = useRef<HTMLInputElement>(null); const [drag, setDrag] = useState(false)
  const add = (files: File[]) => queue.add(files).catch(e => notify(message(e), true))
  return <><div className={`dropzone ${drag ? 'dropzone-active' : ''}`} onDragOver={e => { e.preventDefault(); setDrag(true) }} onDragLeave={() => setDrag(false)} onDrop={e => { e.preventDefault(); setDrag(false); void add([...e.dataTransfer.files]) }}><div className="drop-symbol"><CloudUpload size={36} strokeWidth={1.4} /></div><h2>将文件拖放到这里</h2><p>或者选择设备中的文件，支持多个文件排队上传</p><button className="button primary" onClick={() => input.current?.click()}><Plus size={18} /> 选择文件</button><input ref={input} className="sr-only" type="file" multiple aria-label="选择上传文件" onChange={e => { void add([...e.target.files || []]); e.target.value = '' }} /><span className="drop-info">单文件最大 {bytes(settings.maxFileSize)} <span>·</span> 支持断点续传 <span>·</span> 私有存储</span></div>
    <ErrorBox error={queue.persistenceError} /><section className="upload-queue"><div className="panel-heading"><div><h2>传输队列 <span className="count-badge">{tasks.length}</span></h2><p>刷新后重新选择同一个文件，即可继续上传。</p></div><label className="concurrency-label">并发分片<select aria-label="并发分片数" value={queue.concurrency} onChange={e => queue.setConcurrency(Number(e.target.value))}>{[1, 2, 4, 6, 8].map(n => <option key={n} value={n}>{n}</option>)}</select></label></div>{!tasks.length ? <div className="queue-empty"><Upload size={21} /><span>队列已准备好，等你的下一份文件。</span></div> : tasks.map(t => <UploadCard key={t.key} task={t} queue={queue} select={() => input.current?.click()} onFiles={onFiles} />)}</section>
    <div className="tip-line"><ShieldCheck size={18} /><span>每个分片独立校验。未完成的上传会在 {settings.uploadExpireHours} 小时无活动后自动清理。</span></div>
  </>
}
const statusNames: Record<Task['status'], string> = { queued: '排队中', uploading: '正在上传', paused: '已暂停', 'needs-file': '等待重新选择文件', merging: '正在整理文件', complete: '上传完成', error: '需要重试', canceling: '正在取消' }
function UploadCard({ task: t, queue, select, onFiles }: { task: Task; queue: UploadQueue; select: () => void; onFiles: () => void }) {
  const progress = t.size === 0 ? t.status === 'complete' ? 100 : 0 : Math.min(100, t.uploaded / t.size * 100)
  return <article className="upload-card"><div className="upload-card-main"><span className={`file-icon ${t.status === 'complete' ? 'green' : 'blue'}`}>{t.status === 'complete' ? <Check size={24} /> : <File size={24} />}</span><div className="upload-card-name"><h3 title={t.name}>{t.name}</h3><span>{bytes(t.size)} <b>·</b> <span className={t.status === 'error' ? 'red-text' : ''}>{statusNames[t.status]}</span></span></div><div className="upload-actions">{['uploading', 'queued'].includes(t.status) && <button className="icon-button" aria-label={`暂停 ${t.name}`} onClick={() => queue.pause(t.key)}><Pause size={18} /></button>}{['paused', 'error', 'needs-file'].includes(t.status) && <button className="button compact" onClick={() => t.file ? queue.resume(t.key) : select()}>{t.status === 'error' ? <RefreshCw size={14} /> : <Play size={14} />}{t.file ? t.status === 'error' ? '重试' : '继续' : '重新选择'}</button>}{t.status === 'merging' && <LoaderCircle className="spin" size={19} />}{t.status === 'complete' && <button className="text-button" onClick={onFiles}>去分享 <ArrowUpRight size={14} /></button>}{!['merging', 'canceling'].includes(t.status) && <button className="icon-button" aria-label={`${t.status === 'complete' ? '移除记录' : '取消'} ${t.name}`} onClick={() => t.status === 'complete' ? queue.dismiss(t.key) : void queue.cancel(t.key)}><X size={18} /></button>}</div></div><div className={`progress-track ${t.status === 'complete' ? 'progress-complete' : ''}`}><span style={{ width: `${progress}%` }} /></div><div className="upload-metrics"><span>{bytes(t.uploaded)} / {bytes(t.size)} <b>{progress.toFixed(1)}%</b></span>{t.status === 'uploading' && <><span>即时 {bytes(t.speed)}/s</span><span>平均 {bytes(t.averageSpeed)}/s</span><span>剩余 {duration((t.size - t.uploaded) / t.averageSpeed)}</span><span>{queue.concurrency} 并发</span></>}{t.status === 'merging' && <span>正在校验并保存，完成后即可分享</span>}</div>{t.error && <ErrorBox error={t.error} />}{t.failedChunks.length > 0 && <small className="red-text">失败分片：{t.failedChunks.join(', ')}</small>}</article>
}

interface ShareItem { id: string; url: string; expiresAt: string | null; downloadCount: number; maxDownloads: number; passwordProtected: boolean; revoked: boolean }
function ShareModal({ file, onClose, notify }: { file: FileItem; onClose: () => void; notify: Notify }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [url, setUrl] = useState(''); const [refresh, setRefresh] = useState(0)
  const shares = useResource<ShareItem[]>(`/files/${file.id}/shares`, refresh)
  async function copy(value: string) { try { await navigator.clipboard.writeText(value); notify('分享链接已复制') } catch { setUrl(value); notify('请从文本框中手动复制链接', true) } }
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); setBusy(true); setError(''); try { const result = await api<{ url: string }>(`/files/${file.id}/shares`, { method: 'POST', body: JSON.stringify({ expiresIn: Number(form.get('expiresIn')), password: form.get('password'), maxDownloads: Number(form.get('maxDownloads')) }) }); setUrl(result.url); setRefresh(n => n + 1); notify('分享链接已创建') } catch (e) { setError(message(e)) } finally { setBusy(false) } }
  return <Modal title="分享文件" onClose={onClose}><div className="share-file"><span className="file-icon blue"><File size={24} /></span><div><strong>{file.name}</strong><span>{bytes(file.size)}</span></div></div><form onSubmit={submit}><div className="form-grid"><label>有效期<select name="expiresIn" defaultValue="604800"><option value="3600">1 小时</option><option value="86400">1 天</option><option value="604800">7 天</option><option value="2592000">30 天</option><option value="0">永久有效</option></select></label><label>最大下载次数<input name="maxDownloads" type="number" min="0" max="1000000000" defaultValue="0" /><small>0 为不限次数，每次 GET 请求计一次</small></label></div><label>访问密码 <span className="muted">可选</span><input name="password" type="password" autoComplete="new-password" minLength={12} maxLength={72} placeholder="至少 12 字节，留空则无需密码" /></label><ErrorBox error={error} /><button className="button primary full" disabled={busy}><Link2 size={17} /> {busy ? '正在创建…' : '创建分享链接'}</button></form>{url && <div className="copy-field"><input aria-label="分享链接" readOnly value={url} onFocus={e => e.target.select()} /><button className="icon-button" aria-label="复制分享链接" onClick={() => void copy(url)}><Copy size={18} /></button></div>}<div className="existing-shares"><h3>已有分享</h3><ErrorBox error={shares.error} />{shares.data?.length === 0 && <p className="muted">还没有分享链接。</p>}{shares.data?.map(s => <div className="existing-share" key={s.id}><div><span>{s.passwordProtected ? <LockKeyhole size={13} /> : <Link2 size={13} />} {s.revoked ? '已撤销 / 过期' : `${date(s.expiresAt)}${s.expiresAt ? '到期' : ''}`}</span><small>已下载 {s.downloadCount}{s.maxDownloads ? ` / ${s.maxDownloads}` : ' 次'}</small></div><button className="icon-button" title="复制链接" disabled={s.revoked} onClick={() => void copy(s.url)}><Copy size={16} /></button><button className="icon-button delete-button" title="撤销分享" disabled={s.revoked} onClick={async () => { try { await api(`/shares/${s.id}`, { method: 'DELETE' }); setRefresh(n => n + 1) } catch (e) { notify(message(e), true) } }}><Trash2 size={16} /></button></div>)}</div></Modal>
}

function SettingsPage({ user, settings, queue, notify, onPasswordChanged }: { user: User; settings: Settings; queue: UploadQueue; notify: Notify; onPasswordChanged: () => void }) {
  const [busy, setBusy] = useState(false); const [refresh, setRefresh] = useState(0); const [concurrency, setConcurrency] = useState(queue.concurrency)
  async function password(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); setBusy(true); try { await api('/auth/password', { method: 'POST', body: JSON.stringify({ currentPassword: data.get('current'), newPassword: data.get('new') }) }); onPasswordChanged() } catch (e) { notify(message(e), true) } finally { setBusy(false) } }
  return <div className="settings-grid"><section className="panel settings-panel"><div className="setting-icon"><Settings2 size={22} /></div><h2>传输偏好</h2><p className="muted">选择适合当前网络的上传并发数。</p><label>并发分片<select value={concurrency} onChange={e => { const n = Number(e.target.value); setConcurrency(n); queue.setConcurrency(n); notify('并发设置已更新') }}>{[1, 2, 4, 6, 8].map(n => <option key={n} value={n}>{n} 个分片</option>)}</select></label><dl className="settings-list"><div><dt>单文件上限</dt><dd>{bytes(settings.maxFileSize)}</dd></div><div><dt>分片大小</dt><dd>{bytes(settings.chunkSize)}</dd></div><div><dt>未完成上传保留</dt><dd>{settings.uploadExpireHours} 小时</dd></div><div><dt>磁盘安全预留</dt><dd>{bytes(settings.reservedBytes)}</dd></div></dl></section><section className="panel settings-panel"><div className="setting-icon purple"><LockKeyhole size={22} /></div><h2>账号安全</h2><p className="muted">修改密码后，需要在所有设备重新登录。</p><form onSubmit={password}><label>当前密码<input name="current" type="password" autoComplete="current-password" required /></label><label>新密码<input name="new" type="password" autoComplete="new-password" minLength={12} maxLength={72} required placeholder="12–72 字节" /></label><button className="button" disabled={busy}>更新密码</button></form></section>{user.role === 'admin' && <AdminUsers refresh={refresh} setRefresh={() => setRefresh(n => n + 1)} notify={notify} />}</div>
}
function AdminUsers({ refresh, setRefresh, notify }: { refresh: number; setRefresh: () => void; notify: Notify }) {
  const users = useResource<User[]>('/users', refresh); const [busy, setBusy] = useState(false)
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = e.currentTarget; const data = new FormData(form); setBusy(true); try { await api('/users', { method: 'POST', body: JSON.stringify({ username: data.get('username'), password: data.get('password'), role: data.get('role') }) }); form.reset(); setRefresh(); notify('用户已创建') } catch (e) { notify(message(e), true) } finally { setBusy(false) } }
  return <section className="panel settings-panel admin-panel"><h2>用户管理</h2><p className="muted">为团队创建独立账号，每位用户拥有自己的文件空间。</p><ErrorBox error={users.error} /><div className="user-list">{users.data?.map(u => <div key={u.id}><span className="avatar avatar-small">{u.username.slice(0, 1).toUpperCase()}</span><strong>{u.username}</strong><span className="pill">{u.role === 'admin' ? '管理员' : '普通用户'}</span></div>)}</div><form onSubmit={submit}><div className="form-grid"><label>用户名<input name="username" required minLength={3} maxLength={64} pattern="[A-Za-z0-9_.-]+" placeholder="例如 team_member" autoComplete="off" /></label><label>初始密码<input name="password" type="password" required minLength={12} maxLength={72} autoComplete="new-password" /></label></div><div className="admin-create"><label>角色<select name="role"><option value="user">普通用户</option><option value="admin">管理员</option></select></label><button className="button primary" disabled={busy}><Plus size={16} /> 创建用户</button></div></form></section>
}

interface PublicShare { passwordRequired?: boolean; fileName: string; fileSize: number; uploadedAt: string; expiresAt: string | null; maxDownloads: number; downloadCount: number }
function SharePage({ token }: { token: string }) {
  const [share, setShare] = useState<PublicShare>(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { api<PublicShare>(`/shares/${encodeURIComponent(token)}`).then(setShare).catch(e => setError(message(e))) }, [token])
  async function verify(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(''); const password = new FormData(e.currentTarget).get('password'); try { setShare(await api<PublicShare>(`/shares/${token}/verify`, { method: 'POST', body: JSON.stringify({ password }) })) } catch (e) { setError(message(e)) } finally { setBusy(false) } }
  async function download() { setBusy(true); setError(''); try { const response = await fetch(`/api/download/${token}`, { method: 'HEAD', credentials: 'same-origin' }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error || '分享已失效') }; const a = document.createElement('a'); a.href = `/api/download/${token}`; a.download = share?.fileName || ''; document.body.appendChild(a); a.click(); a.remove() } catch (e) { setError(message(e)) } finally { setBusy(false) } }
  return <div className="share-page"><header><Logo /><span className="secure-label"><ShieldCheck size={16} /> 私密分享</span></header><main className="share-public-card"><span className="eyebrow">SOMETHING GOOD, SHARED.</span><div className="share-hero-icon">{share?.passwordRequired ? <LockKeyhole size={42} strokeWidth={1.3} /> : <File size={46} strokeWidth={1.2} />}</div>{share?.passwordRequired ? <><h1>这份分享，设有密码。</h1><p className="muted">输入发送者提供的密码，查看并下载文件。</p><form onSubmit={verify}><label className="sr-only" htmlFor="share-password">分享密码</label><input id="share-password" name="password" type="password" autoFocus autoComplete="off" required maxLength={72} placeholder="输入访问密码" /><button className="button primary full" disabled={busy}>解锁文件 <ArrowUpRight size={17} /></button></form></> : share ? <><h1 title={share.fileName}>{share.fileName}</h1><div className="share-size">{bytes(share.fileSize)}</div><dl className="share-details"><div><dt>上传时间</dt><dd>{date(share.uploadedAt)}</dd></div><div><dt>有效期至</dt><dd>{date(share.expiresAt)}</dd></div>{share.maxDownloads > 0 && <div><dt>剩余下载次数</dt><dd>{Math.max(0, share.maxDownloads - share.downloadCount)}</dd></div>}</dl><button className="button primary full" disabled={busy} onClick={download}><ArrowDownToLine size={19} /> 下载文件</button></> : !error ? <Spinner /> : <><h1>这份分享暂时无法打开</h1><p className="muted">请联系发送者获取新的分享链接。</p></>}<ErrorBox error={error} /><div className="share-security"><ShieldCheck size={15} /> 由 LinkBox Send 安全传递</div></main><footer>Small link. Big possibilities.</footer></div>
}
