import { test, expect } from '@playwright/test'
import { mkdir, writeFile, readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { createHash } from 'node:crypto'

test('real upload, pause/reload/resume, password share, Range and mobile layout', async ({ page, browser }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await page.getByLabel('用户名', { exact: true }).fill('admin')
  await page.getByLabel('密码', { exact: true }).fill('e2e-local-test-password')
  await page.getByRole('button', { name: '登录空间' }).click()
  await expect(page.getByRole('heading', { name: '每一份文件，都有去处。' })).toBeVisible()
  await page.screenshot({ path: '../.tools/screenshots/dashboard-desktop.png', fullPage: true })
  await page.locator('nav').getByRole('button', { name: '上传文件' }).click()
  await page.getByLabel('并发分片数').selectOption('1')
  const filePath = resolve('../.tools/e2e-resume-测试.bin')
  const content = Buffer.alloc(33 * 1024 * 1024 + 101, 0x5a)
  content.write('LinkBox Send real browser transfer')
  await writeFile(filePath, content)
  // Delay only the second real request, creating a deterministic window to pause.
  await page.route('**/chunks/1', async route => { await new Promise(r => setTimeout(r, 2500)); await route.continue().catch(() => {}) })
  const first = page.waitForResponse(r => r.url().endsWith('/chunks/0') && r.status() === 204)
  await page.getByLabel('选择上传文件').setInputFiles(filePath)
  await first
  await page.getByRole('button', { name: '暂停 e2e-resume-测试.bin', exact: true }).click()
  await expect(page.getByText('已暂停', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('等待重新选择文件', { exact: true })).toBeVisible()
  const chunkRequests: string[] = []
  page.on('request', request => { if (request.method() === 'PUT') chunkRequests.push(request.url()) })
  await page.unroute('**/chunks/1')
  await page.getByLabel('选择上传文件').setInputFiles(filePath)
  await expect(page.getByText('上传完成', { exact: true })).toBeVisible({ timeout: 60_000 })
  expect(chunkRequests.some(url => url.endsWith('/chunks/0'))).toBe(false)
  expect(chunkRequests.some(url => url.endsWith('/chunks/1'))).toBe(true)
  await page.screenshot({ path: '../.tools/screenshots/upload-desktop.png', fullPage: true })
  await page.getByRole('button', { name: '去分享' }).click()
  await page.getByRole('button', { name: '分享 e2e-resume-测试.bin', exact: true }).click()
  await page.getByLabel('访问密码').fill('browser-share-password')
  await page.getByRole('button', { name: '创建分享链接', exact: true }).click()
  const link = page.getByLabel('分享链接', { exact: true })
  await expect(link).toBeVisible()
  const shareURL = await link.inputValue()
  const visitor = await browser.newContext({ acceptDownloads: true })
  const shared = await visitor.newPage()
  await shared.goto(shareURL)
  await expect(shared.getByRole('heading', { name: '这份分享，设有密码。' })).toBeVisible()
  await shared.getByLabel('分享密码', { exact: true }).fill('browser-share-password')
  await shared.getByRole('button', { name: '解锁文件' }).click()
  await expect(shared.getByRole('heading', { name: 'e2e-resume-测试.bin' })).toBeVisible()
  const downloadEvent = shared.waitForEvent('download')
  await shared.getByRole('button', { name: '下载文件', exact: true }).click()
  const download = await downloadEvent
  const disk = await download.path()
  expect(disk).not.toBeNull()
  expect(createHash('sha256').update(await readFile(disk!)).digest('hex')).toBe(createHash('sha256').update(content).digest('hex'))
  const token = new URL(shareURL).pathname.split('/')[2]
  const range = await visitor.request.get(`http://localhost:18773/api/download/${token}`, { headers: { Range: 'bytes=2-9' } })
  expect(range.status()).toBe(206)
  expect(await range.body()).toEqual(content.subarray(2, 10))
  await shared.setViewportSize({ width: 390, height: 844 })
  await shared.screenshot({ path: '../.tools/screenshots/share-mobile.png', fullPage: true })
  expect(await shared.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '每一份文件，都有去处。' })).toBeVisible()
  await page.screenshot({ path: '../.tools/screenshots/dashboard-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
  await visitor.close()
  await mkdir(resolve('../.tools/screenshots'), { recursive: true })
})
